version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  make-a-story:
    lang: java11
    handler: ./make-a-story
    image: sc20jh/make-a-story:latest
  email-users:
    lang: java11
    handler: ./email-users
    image: sc20jh/email-users:latest
  generate-summary:
    lang: java11
    handler: ./generate-summary
    image: sc20jh/generate-summary:latest

  


